### PR TITLE
Bug/token value 739

### LINKED ISSUE #739: The total amount of tokens are not registered on the Token Viz Dashboard
**Preconditions:**
Users have taken the token assessment and selected positive token values
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (garry@ml.com // 123456)
2. Select the TOKENLOGGER(+&-) applet
3. Select a user and navigate to the token Viz Dashboard (Applet pass: Qwe123!!!)
4. Look at the graph

**Actual:** The total amount of tokens are not registered on the Token Viz Dashboard. It shows "0" tokens

**Expected:** The total amount of tokens are registered on the Token Viz Dashboard. 

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 // Chrome 87

### PR DESCRIPTION
**Pull request by Matchdev120**
Resolved #739

### CODE REVIEW

File: src/State/state.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ import createPersistedState from 'vuex-persistedstate';
 
 const getDefaultState = () => {
   return {
-    backend: process.env.VUE_APP_SERVER_URL,
+    backend: "https://api-staging.mindlogger.org/api/v1",
```
Comment (devbtech) [inline src/State/state.js]: What is this change for? default backend server url should be read from env files.

File: src/State/state.js [hunk 2]
```diff
@@ -68,7 +68,7 @@ const mutations = {
     //   _.find(backendServers, { env: process.env.NODE_ENV }).url ||
     //   backendServers[0].url;
 
-    state.backend = backend || process.env.VUE_APP_SERVER_URL;
+    state.backend = backend || "https://api-staging.mindlogger.org/api/v1";
```
Comment (devbtech) [inline src/State/state.js]: What is this change for? default backend server url should be read from env files.
